### ISSUE TITLE
assertion failure: module system failed to initialise - see radiant.log for error messages

### ISSUE THREAD

**Issue by MarkovType** [kasymovga/rexradiant#1]
Hello,
Just downloaded the latest release for Linux, and I had to install the following packages : `libgtkglext1` and `libpangox` (from this [website](http://technoworkshop.in/solved-error-while-loading-shared-libraries-libpangox-1-0-so-0-anydesk-on-ubuntu-22-04-lts/)) to make it start. However, I get the following log error : 

`
Started logging to /home/name/.netradiant/1.5.0/radiant.log
Today is: Sat Jun 10 20:41:23 2023
This is NetRadiant '1.5.0n-git-1480fc9' compiled May 10 2022
Custom build
loading local preferences from /home/name/.netradiant/1.5.0/rexuiz.game/local.pref
failed to load local preferences from /home/name/.netradiant/1.5.0/rexuiz.game/local.pref
Module Registered: type="brush" version="1" name="doom3"
Module Registered: type="brush" version="1" name="quake4"
Module Registered: type="brush" version="1" name="quake3"
Module Registered: type="brush" version="1" name="quake2"
Module Registered: type="brush" version="1" name="quake"
Module Registered: type="brush" version="1" name="halflife"
Module Registered: type="eclass" version="1" name="def"
Module Registered: type="eclassmanager" version="1" name="doom3"
Module Registered: type="eclassmanager" version="1" name="halflife"
Module Registered: type="eclassmanager" version="1" name="quake3"
Module Registered: type="eclass" version="1" name="xml"
Module Registered: type="filetypes" version="1" name="*"
Module Registered: type="filters" version="1" name="*"
Module Registered: type="gtkgl" version="1" name="*"
Module Registered: type="namespace" version="1" name="*"
Module Registered: type="scriptlib" version="1" name="*"
Module Registered: type="patch" version="1" name="quake3"
Module Registered: type="patch" version="1" name="doom3"
Module Registered: type="patch" version="1" name="def2doom3"
Module Registered: type="camera" version="1" name="*"
Module Registered: type="radiant" version="1" name="*"
Module Registered: type="preferences" version="1" name="*"
Module Registered: type="qgl" version="2" name="*"
Module Registered: type="reference" version="1" name="*"
Module Registered: type="openglshaderlibrary" version="1" name="*"
Module Registered: type="renderstate" version="1" name="*"
Module Registered: type="scenegraph" version="1" name="*"
Module Registered: type="selection" version="1" name="*"
Module Registered: type="textures" version="1" name="*"
Module Registered: type="undo" version="1" name="*"
Module Initialising: 'radiant' '*'
Module Ready: 'radiant' '*'
Module Initialising: 'VFS' '*'
Module Initialising: 'archive' 'pk3'
Module Ready: 'archive' 'pk3'
Module Ready: 'VFS' '*'
Module Initialising: 'entity' 'quake3'
Module Initialising: 'qgl' '*'
Module Ready: 'qgl' '*'
Module Initialising: 'undo' '*'
Module Initialising: 'preferences' '*'
Module Ready: 'preferences' '*'
Module Ready: 'undo' '*'
Module Initialising: 'scenegraph' '*'
Module Ready: 'scenegraph' '*'
Module Initialising: 'renderstate' '*'
Module Initialising: 'shaders' 'quake3'
Module Initialising: 'textures' '*'
ModulesRef::initialise: type="image" version="1" name="tga" - not found
ModulesRef::initialise: type="image" version="1" name="jpg" - not found
ModulesRef::initialise: type="image" version="1" name="png" - not found
Module Ready: 'textures' '*'
Module Initialising: 'scriptlib' '*'
Module Ready: 'scriptlib' '*'
ModuleRef::initialise: type="image" version="1" name="png" - not found
Module Dependencies Failed: 'shaders' 'quake3'
Module Dependencies Failed: 'renderstate' '*'
Module Dependencies Failed: 'entity' 'quake3'
radiant/mainframe.cpp:629
assertion failure: module system failed to initialise - see radiant.log for error messages

./radiant.x86_64() [0x5d3944]
./radiant.x86_64() [0x5123f4]
./radiant.x86_64() [0x509d59]
./radiant.x86_64() [0x42fff9]
/lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7fc29af2fd90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7fc29af2fe40]
./radiant.x86_64() [0x443a75]

failed to load custom shortcuts from "/home/name/.netradiant/1.5.0/rexuiz.game/shortcuts.ini"
radiant/commands.cpp:80
assertion failure: failed to lookup command "GridDown"

./radiant.x86_64() [0x5d3944]
./radiant.x86_64() [0x5123f4]
./radiant.x86_64() [0x4a9b2f]
./radiant.x86_64() [0x4fb05f]
./radiant.x86_64() [0x4f3080]
./radiant.x86_64() [0x5043d9]
./radiant.x86_64() [0x50b04f]
./radiant.x86_64() [0x430021]
/lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7fc29af2fd90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7fc29af2fe40]
./radiant.x86_64() [0x443a75]

`

I am using this system : 
`OS: Linux Mint 21.1 x86_64 
Host: ThinkPad L470
Kernel: 5.15.0-73-generic 
Shell: bash 5.1.16 
Resolution: 1366x768 
DE: Plasma 5.24.7 
WM: KWin 
CPU: Intel i5-6200U (4) @ 2.800GHz 
GPU: Intel Skylake GT2 [HD Graphics 5 
Memory: 5116MiB / 7830MiB 
`

What should I do ?

Thanks for your attention.

**Comment by MarkovType** [comment]
Using an older version works for me.

**Comment by kasymovga** [comment]
Looks like there is some issues with symlinks in .zip archives in Ubuntu. I replaced it with .tar.gz.
